/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-20 18:20:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.tap.cartitem.CartItem;
import com.tap.user.User;
import com.tap.security.Security;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.tap.user.User");
    _jspx_imports_classes.add("com.tap.cartitem.CartItem");
    _jspx_imports_classes.add("com.tap.security.Security");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Checkout</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap 5 CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General Styling */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #f5f7fa, #c3cfe2);\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Header Styling */\r\n");
      out.write("        header {\r\n");
      out.write("            background: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header h1 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 2.5em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container for Checkout */\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table td, .table th {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-section h2 {\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-section {\r\n");
      out.write("            padding-bottom: 20px;\r\n");
      out.write("            border-bottom: 2px solid #007bff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("            border-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back {\r\n");
      out.write("            background-color: #6c757d;\r\n");
      out.write("            border-color: #6c757d;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back:hover {\r\n");
      out.write("            background-color: #5a6268;\r\n");
      out.write("            border-color: #5a6268;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method label {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method input[type=\"radio\"] {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method i {\r\n");
      out.write("            font-size: 1.5em;\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animation */\r\n");
      out.write("        .fade-in {\r\n");
      out.write("            animation: fadeIn 0.5s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from {\r\n");
      out.write("                opacity: 0;\r\n");
      out.write("                transform: translateY(20px);\r\n");
      out.write("            }\r\n");
      out.write("            to {\r\n");
      out.write("                opacity: 1;\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive */\r\n");
      out.write("        @media (max-width: 600px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("            }\r\n");
      out.write("            header h1 {\r\n");
      out.write("                font-size: 2em;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <h1>Checkout</h1>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container fade-in\">\r\n");
      out.write("    <!-- Order Summary -->\r\n");
      out.write("    <div class=\"order-summary\">\r\n");
      out.write("        <h2>Order Summary</h2>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Item</th>\r\n");
      out.write("                    <th>Quantity</th>\r\n");
      out.write("                    <th>Price</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
	
                	User user = (User) session.getAttribute("loggedInUser");
                    Map<Integer, CartItem> cart = (Map<Integer, CartItem>) session.getAttribute("cart");
                    double totalAmount = 0.0;

                    if (cart != null && !cart.isEmpty()) {
                        for (CartItem item : cart.values()) {
                            double itemTotal = item.getPrice() * item.getQuantity();
                            totalAmount += itemTotal;
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( item.getName() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( item.getQuantity() );
      out.write("</td>\r\n");
      out.write("                    <td>$");
      out.print( String.format("%.2f", itemTotal) );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                        }
                    } else {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\">Your cart is empty.</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        <h3>Total Amount: $");
      out.print( String.format("%.2f", totalAmount) );
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Back Button -->\r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("        <a href=\"home.jsp\" class=\"btn btn-back\"><i class=\"fas fa-arrow-left\"></i> Back to Shopping</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Shipping Information -->\r\n");
      out.write("    <div class=\"form-section\">\r\n");
      out.write("        <h2>Shipping Information</h2>\r\n");
      out.write("        <form action=\"placeOrder\" method=\"post\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"firstName\">First Name:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"firstName\" name=\"firstName\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"lastName\">Last Name:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"lastName\" name=\"lastName\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"email\">Email:</label>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" value=\"");
      out.print( Security.decryption(user.getEmail()) );
      out.write("\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"phone\">Phone:</label>\r\n");
      out.write("                    <input type=\"tel\" id=\"phone\" name=\"phone\" class=\"form-control\" value=\"");
      out.print( Security.decryption(user.getMobile()) );
      out.write("\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"address\">Address:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"address\" name=\"address\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"city\">City:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"city\" name=\"city\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"state\">State:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"state\" name=\"state\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <label for=\"zip\">Zip Code:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"zip\" name=\"zip\" class=\"form-control\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Payment Method -->\r\n");
      out.write("            <h2>Payment Method</h2>\r\n");
      out.write("            <div class=\"payment-method\">\r\n");
      out.write("                <label>\r\n");
      out.write("                    <input type=\"radio\" name=\"paymentMethod\" value=\"creditCard\" required> \r\n");
      out.write("                    <!-- <i class=\"fab fa-cc-visa\"></i> --> <img src=\"https://w7.pngwing.com/pngs/29/61/png-transparent-visa-logo-visa-credit-card-mastercard-logo-visa-cdr-text-rectangle-thumbnail.png\" alt=\"Paytm\" width=\"40\" /> Credit Card\r\n");
      out.write("                </label>\r\n");
      out.write("                <label>\r\n");
      out.write("                    <input type=\"radio\" name=\"paymentMethod\" value=\"debitCard\"> \r\n");
      out.write("                    <!-- <i class=\"fab fa-cc-mastercard\"></i> --> <img src=\"https://w7.pngwing.com/pngs/648/903/png-transparent-mastercard-logo-logo-payment-visa-mastercard-paypal-mastercard-icon-text-service-mobile-payment-thumbnail.png\" alt=\"Paytm\" width=\"40\" /> Debit Card\r\n");
      out.write("                </label>\r\n");
      out.write("                <label>\r\n");
      out.write("                    <input type=\"radio\" name=\"paymentMethod\" value=\"paypal\"> \r\n");
      out.write("                    <!-- <i class=\"fab fa-paypal\"></i> --> <img src=\"https://w7.pngwing.com/pngs/201/983/png-transparent-paypal-android-aptoide-paypal-thumbnail.png\" alt=\"Paytm\" width=\"40\" /> PayPal\r\n");
      out.write("                </label>\r\n");
      out.write("                <label>\r\n");
      out.write("                    <input type=\"radio\" name=\"paymentMethod\" value=\"upi\"> \r\n");
      out.write("                    <img src=\"https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/upi-icon.png\" alt=\"UPI\" width=\"40\" /> UPI (Google Pay, PhonePe, Paytm)\r\n");
      out.write("                </label>\r\n");
      out.write("                <label>\r\n");
      out.write("                    <input type=\"radio\" name=\"paymentMethod\" value=\"razorpay\"> \r\n");
      out.write("                    <img src=\"https://w7.pngwing.com/pngs/586/552/png-transparent-razorpay-hd-logo-thumbnail.png\" alt=\"Razorpay\" width=\"40\" />   Razorpay\r\n");
      out.write("                </label>\r\n");
      out.write("                <label>\r\n");
      out.write("                    <input type=\"radio\" name=\"paymentMethod\" value=\"paytm\"> \r\n");
      out.write("                    <img src=\"https://w7.pngwing.com/pngs/110/280/png-transparent-paytm-standalone-hd-logo-thumbnail.png\" alt=\"Paytm\" width=\"40\" />   Paytm\r\n");
      out.write("                </label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"hidden\" name=\"totalAmount\" value=\"");
      out.print( String.format("%.2f", totalAmount) );
      out.write("\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-lg\">Place Order</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap 5 JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
