/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-20 17:52:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.tap.menu.Menu;

public final class getMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.tap.menu.Menu");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Menu Details</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General Styling */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #f6d365 0%, #fda085 100%);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Header Styling */\r\n");
      out.write("        header {\r\n");
      out.write("            background: #2C3E50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header h1 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 2.5em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Back Button Styling */\r\n");
      out.write("        .back-button {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            left: 20px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background: #FF5722;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.3s ease;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-button:hover {\r\n");
      out.write("            background: #E64A19;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Cart Icon Styling */\r\n");
      out.write("        .cart-icon {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 20px;\r\n");
      out.write("            right: 65px;\r\n");
      out.write("            background: #FF5722;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: transform 0.3s ease, background 0.3s ease;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-icon:hover {\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("            background: #E64A19;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .item-count {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -10px;\r\n");
      out.write("            right: -10px;\r\n");
      out.write("            background: #FF5722;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            padding: 3px 8px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Grid Container for Cards */\r\n");
      out.write("        .container {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(4, 1fr); /* 4 cards per row */\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            justify-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Card Styling */\r\n");
      out.write("        .card {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 350px;\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 15px 30px rgba(0, 0, 0, 0.25);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-body {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card h2 {\r\n");
      out.write("            font-size: 1.8em;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price {\r\n");
      out.write("            font-size: 1.4em;\r\n");
      out.write("            color: #FF5722;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .rating {\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            color: #FFC107;\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .availability {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .available {\r\n");
      out.write("            color: #4CAF50;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .not-available {\r\n");
      out.write("            color: #E74C3C;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .add-to-cart {\r\n");
      out.write("            background: #28a745;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.3s ease;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .add-to-cart:hover {\r\n");
      out.write("            background: #218838;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-selector {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-selector select {\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer Styling */\r\n");
      out.write("        footer {\r\n");
      out.write("            background: rgba(44, 62, 80, 0.9);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer p {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .social-icons a {\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("            color: #08eee5;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            transition: color 0.3s;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .social-icons a:hover {\r\n");
      out.write("            color: #ff5722;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <h1>Menu Details</h1>\r\n");
      out.write("    <button class=\"back-button\" onclick=\"window.location.href='home.jsp';\">Back</button>\r\n");
      out.write("    <button class=\"cart-icon\" onclick=\"window.location.href='cart.jsp';\">\r\n");
      out.write("        <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("        ");
 
            Integer cartItemCount = (Integer) session.getAttribute("cartItemCount");
            if (cartItemCount != null && cartItemCount > 0) { 
        
      out.write("\r\n");
      out.write("            <span class=\"item-count\">");
      out.print( cartItemCount );
      out.write("</span>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </button>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");

        List<Menu> mList = (List<Menu>) session.getAttribute("menuList");
        if (mList != null && !mList.isEmpty()) {
            for (Menu mnu : mList) {
    
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <img src=\"");
      out.print( mnu.getImage() );
      out.write("\" alt=\"");
      out.print( mnu.getMenuName() );
      out.write("\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h2>");
      out.print( mnu.getMenuName() );
      out.write("</h2>\r\n");
      out.write("                <p><strong>Description:</strong> ");
      out.print( mnu.getDescription() );
      out.write("</p>\r\n");
      out.write("                <p class=\"price\">₹");
      out.print( Math.round(mnu.getPrice() * 10) );
      out.write("</p>\r\n");
      out.write("                <p class=\"rating\">Rating: ");
      out.print( mnu.getRating() );
      out.write(" / 5</p>\r\n");
      out.write("                <p class=\"availability ");
      out.print( mnu.isAvailable() ? "available" : "not-available" );
      out.write("\">\r\n");
      out.write("                    ");
      out.print( mnu.isAvailable() ? "Available" : "Not Available" );
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("                <div class=\"quantity-selector\">\r\n");
      out.write("                    <form action=\"addcartcntrl\" method=\"post\">\r\n");
      out.write("                        <select name=\"quantity\">\r\n");
      out.write("                            ");
 for (int i = 1; i <= 10; i++) { 
      out.write("\r\n");
      out.write("                                <option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</option>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <input type=\"hidden\" name=\"id\" value=\"");
      out.print( mnu.getMenuId() );
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"img\" value=\"");
      out.print( mnu.getImage() );
      out.write("\">\r\n");
      out.write("                        <button type=\"submit\" class=\"add-to-cart\">Add to Cart</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 
            }
        } else {
            out.println("<p>No menu items available.</p>");
        }
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <p>&copy; 2024 Your Restaurant App. All rights reserved.</p>\r\n");
      out.write("    <div class=\"social-icons\">\r\n");
      out.write("        <a href=\"#\" class=\"fab fa-facebook-f\"></a>\r\n");
      out.write("        <a href=\"#\" class=\"fab fa-twitter\"></a>\r\n");
      out.write("        <a href=\"#\" class=\"fab fa-instagram\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
